import { Upgrade } from '../types';

const upgrades: Upgrade[] = [
  {
    ldf: 'dlt19stormtrooper',
    name: 'DLT-19 Stormtrooper',
    slot: 'Heavy Weapon',
    points: 24,
    restrictions: { name: 'Stormtroopers only', ldf: 'stormtroopers' },
    description: 'Add 1 DLT-19 Stormtrooper mini',
    keywords: ['Impact 1'],
    weapon: {
      range: { from: 1, to: 4 },
      dice: { red: 2 },
    },
  },
  {
    ldf: 'hh12stormtrooper',
    name: 'HH-12 Stormtrooper',
    exhaust: true,
    slot: 'Heavy Weapon',
    restrictions: { name: 'Stormtroopers only', ldf: 'stormtroopers' },
    description: 'Add 1 HH-12 Stormtrooper mini',
    points: 26,
    keywords: ['Cumbersome', 'Impact 3'],
    weapon: {
      range: { from: 2, to: 4 },
      dice: { black: 3 },
    },
  },
  {
    ldf: 'mpl57iontrooper',
    name: 'MPL-57 Ion Trooper',
    side: 'light',
    slot: 'Heavy Weapon',
    points: 24,
    exhaust: true,
    restrictions: { name: 'Rebel Troopers only', ldf: 'rebeltroopers' },
    description: 'Add 1 MPL-57 ion trooper figure',
    keywords: ['Impact 1','Ion 1'],
    weapon: {
      range: { from: 1, to: 3 },
      dice: { red: 2 },
    },
  },
  {
    ldf: 'z6trooper',
    name: 'Z-6 Trooper',
    slot: 'Heavy Weapon',
    restrictions: { name: 'Rebel Troopers only', ldf: 'rebeltroopers' },
    points: 22,
    description: 'Add 1 Z-6 Trooper mini',
    weapon: {
      range: { from: 1, to: 3 },
      dice: { white: 6 },
    },
  },
  {
    ldf: 't7ionsnowtrooper',
    name: 'T-7 Ion Snowtrooper',
    slot: 'Heavy Weapon',
    points: 26,
    exhaust: true,
    restrictions: { name: 'Snowtroopers only', ldf: 'snowtroopers' },
    description: 'Add 1 T-7 Ion trooper figure',
    keywords: ['Impact 1', 'Ion 1'],
    weapon: {
      range: { from: 1, to: 3 },
      dice: { black: 1, white: 2 },
    },
  },
  {
    ldf: 'scatterguntrooper',
    name: 'Scatter Gun Trooper',
    slot: 'Heavy Weapon',
    points: 23,
    restrictions: { name: 'Fleet Troopers only', ldf: 'fleettroopers' },
    description: 'Add 1 Scatter Gun Trooper figure',
    keywords: ['Pierce 1'],
    weapon: {
      range: { from: 1, to: 2 },
      dice: { red: 2 },
    },
  },
  {
    ldf: 'mpl57barragetrooper',
    name: 'MPL-57 Barrage Trooper',
    slot: 'Heavy Weapon',
    points: 25,
    restrictions: { name: 'Fleet Troopers only', ldf: 'fleettroopers' },
    description: 'Add 1 MPL-57 barrage trooper mini',
    exhaust: true,
    keywords: ['Blast', 'Impact 2'],
    weapon: {
      range: { from: 1, to: 3 },
      dice: { black: 1, white: 2 },
    },
  },
  {
    ldf: 'flametrooper',
    name: 'Flametrooper',
    slot: 'Heavy Weapon',
    points: 20,
    restrictions: { name: 'Snowtroopers only', ldf: 'snowtroopers' },
    description: 'Add 1 Flametrooper figure',
    keywords: ['Blast', 'Spray'],
    weapon: {
      range: { from: 1 },
      dice: { black: 1 },
    },
  },
  {
    ldf: 'dh447sniper',
    name: 'DH-447 Sniper',
    slot: 'Heavy Weapon',
    points: 28,
    restrictions: { name: 'Rebel Commandos only', ldf: 'rebelcommandos' },
    description: 'Add 1 DH-447 Sniper mini',
    keywords: ['High Velocity', 'Pierce 1'],
    weapon: {
      range: { from: 1, to: 5 },
      dice: { black: 1, white: 1 },
    },
  },
  {
    ldf: 'protonchargesaboteur',
    name: 'Proton Charge Saboteur',
    slot: 'Heavy Weapon',
    points: 26,
    restrictions: { name: 'Rebel Commandos only', ldf: 'rebelcommandos' },
    description: 'Add 1 Proton Charge Saboteur mini',
    keywords: ['Arm 1: Proton Charge', 'Detonate 1: Proton Charge', 'Blast', 'Impact 1'],
    weapon: {
      range: { from: 1, to: 1 },
      dice: { red: 1, white: 2 },
    },
  },
  {
    ldf: 'electrostaffguard',
    name: 'Electrostaff Guard',
    slot: 'Heavy Weapon',
    points: 25,
    restrictions: {
      name: 'Imperial Royal Guards only',
      ldf: 'imperialroyalguards',
    },
    description:
      'Add 1 electrostaff guard mini. While defending against a melee attack, you gain <strong>Immune: Pierce</strong> (Pierce cannot be used against you.)',
    keywords: ['Sidearm: Melee'],
    weapon: {
      range: { from: 0 },
      dice: { black: 2 },
    },
  },
  {
    ldf: 'dlt19xsniper',
    name: 'DLT-19x Sniper',
    slot: 'Heavy Weapon',
    points: 28,
    restrictions: { name: 'Scout Troopers only', ldf: 'scouttroopers' },
    description: 'Add 1 DLT-19x sniper mini.',
    keywords: ['High Velocity', 'Pierce 1'],
    weapon: {
      range: { from: 1, to: 5 },
      dice: { black: 2 },
    },
  },
  {
    ldf: 'sonicchargesaboteur',
    name: 'Sonic Charge Saboteur',
    slot: 'Heavy Weapon',
    points: 26,
    restrictions: { name: 'Scout Troopers only', ldf: 'scouttroopers' },
    description: 'Add 1 sonic charge saboteur mini.',
    keywords: ['Arm 1: Sonic Charge', 'Detonate 1: Sonic Charge', 'Blast', 'Suppressive'],
    weapon: {
      range: { from: 1 },
      dice: { black: 1, red: 1 },
    },
  },
  {
    ldf: 'bowcasterwookiee',
    name: 'Bowcaster Wookiee',
    slot: 'Heavy Weapon',
    points: 35,
    restrictions: { name: 'Wookiee Warriors only', ldf: 'bowcasterwookiee' },
    description: 'Add 1 bowcaster wookiee mini.',
    keywords: ['Impact 1', 'Pierce 1'],
    weapon: {
      range: { from: 1, to: 3 },
      dice: { red: 1, white: 1 },
    },
  },
  {
    ldf: 'bistan',
    name: 'Bistan',
    slot: 'Heavy Weapon',
    points: 32,
    unique: true,
    restrictions: { name: 'Rebel Pathfinders only', ldf: 'rebelpathfinders' },
    description: 'Add 1 Bistan mini.',
    exhaust: true,
    keywords: ['Impact 1', 'Ion 1'],
    weapon: {
      range: { from: 1, to: 4 },
      dice: { black: 1, white: 4 },
    },
  },
  {
    ldf: 'pao',
    name: 'Pao',
    side: 'light',
    slot: 'Heavy Weapon',
    points: 22,
    unique: true,
    restrictions: { name: 'Rebel Pathfinders only', ldf: 'rebelpathfinders' },
    description: 'Add 1 Pao mini.',
    exhaust: true,
    keywords: ['Inspire 1', 'Leader'],
    weapon: {
      range: { from: 1, to: 4 },
      dice: { red: 1, white: 1 },
    },
  },
  {
    ldf: 'dtf16',
    name: 'DT-F16',
    slot: 'Heavy Weapon',
    points: 22,
    unique: true,
    restrictions: {
      name: 'Imperial Death Troopers only',
      ldf: 'imperialdeathtroopers',
    },
    description: 'Add 1 DT-F16 mini.',
    keywords: ['Compel', 'Leader'],
    weapon: {
      range: { from: 1, to: 3 },
      dice: { black: 1, white: 1 },
    },
  },
  {
    ldf: 'dlt19dtrooper',
    name: 'DLT-19D Trooper',
    slot: 'Heavy Weapon',
    points: 34,
    restrictions: {
      name: 'Imperial Death Troopers only',
      ldf: 'imperialdeathtroopers',
    },
    description: 'Add 1 DLT-19D trooper mini.',
    keywords: ['Impact 1'],
    weapon: {
      range: { from: 1, to: 4 },
      dice: { red: 2, white: 1 },
    },
  },
  {
    ldf: 'cmo93trooper',
    name: 'CM-O/93 Trooper',
    slot: 'Heavy Weapon',
    points: 26,
    restrictions: {
      name: 'Rebel Veterans only',
      ldf: 'rebelveterans',
    },
    description: 'Add 1 CM-O/93 trooper mini.',
    keywords: ['Critical 2'],
    weapon: {
      range: { from: 1, to: 3 },
      dice: { white: 4 },
    },
  },
  {
    ldf: 't21btrooper',
    name: 'T-21B Trooper',
    slot: 'Heavy Weapon',
    points: 32,
    restrictions: {
      name: 'Shoretroopers only',
      ldf: 'shoretroopers',
    },
    description: 'Add 1 T-21B trooper mini.',
    keywords: ['Critical 1'],
    weapon: {
      range: { from: 1, to: 4 },
      dice: { white: 2, black: 2 },
    },
  },
  {
    ldf: 'dc15phaseitrooper',
    name: 'DC-15 Phase I Trooper',
    slot: 'Heavy Weapon',
    points: 30,
    restrictions: {
      name: 'Phase I Clone Troopers only',
      ldf: 'phaseiclonetroopers',
    },
    description: 'Add 1 DC-15 Phase I trooper mini.',
    keywords: ['Critical 1'],
    weapon: {
      range: { from: 1, to: 4 },
      dice: { red: 2 },
    },
  },
  {
    ldf: 'z6phaseitrooper',
    name: 'Z-6 Phase I Trooper',
    slot: 'Heavy Weapon',
    points: 25,
    restrictions: {
      name: 'Phase I Clone Troopers only',
      ldf: 'phaseiclonetroopers',
    },
    description: 'Add 1 Z-6 Phase I trooper mini.',
    weapon: {
      range: { from: 1, to: 3 },
      dice: { white: 6 },
    },
  },
  {
    ldf: 'e5cb1trooper',
    name: 'E-5C B1 Trooper',
    slot: 'Heavy Weapon',
    points: 18,
    restrictions: {
      name: 'B1 Battle Droids only.',
      ldf: 'b1battledroids',
    },
    description: 'Add 1 E-5C B1 trooper mini.',
    weapon: {
      range: { from: 1, to: 3 },
      dice: { black: 3 },
    },
  },
  {
    ldf: 'e60rb1trooper',
    name: 'E-60R B1 Trooper',
    slot: 'Heavy Weapon',
    points: 20,
    exhaust: true,
    restrictions: {
      name: 'B1 Battle Droids only.',
      ldf: 'b1battledroids',
    },
    description: 'Add 1 E-60R B1 trooper mini.',
    keywords: ['Impact 2'],
    weapon: {
      range: { from: 2, to: 4 },
      dice: { red: 1, black: 2 },
    },
  },
];

export default upgrades;
