import { Upgrade } from '../types';

const upgrades: Upgrade[] = [
  {
    ldf: 'rebeltrooper',
    name: 'Rebel Trooper',
    slot: 'Personnel',
    points: 10,
    restrictions: { name: 'Rebel Troopers only', ldf: 'rebeltroopers' },
    description: 'Add 1 Rebel Trooper mini',
  },
  {
    ldf: 'stormtrooper',
    name: 'Stormtrooper',
    slot: 'Personnel',
    points: 11,
    restrictions: { name: 'Stormtroopers only', ldf: 'stormtroopers' },
    description: 'Add 1 Stormtrooper mini.',
  },
  {
    ldf: 'snowtrooper',
    name: 'Snowtrooper',
    slot: 'Personnel',
    points: 12,
    restrictions: { name: 'Snowtroopers only', ldf: 'snowtroopers' },
    description: 'Add 1 Snowtrooper mini.',
  },
  {
    ldf: 'fleettrooper',
    name: 'Fleet Trooper',
    slot: 'Personnel',
    points: 11,
    restrictions: { name: 'Fleet Troopers only', ldf: 'fleettroopers' },
    description: 'Add 1 Fleet Trooper mini.',
  },
  {
    ldf: 'rebelofficer',
    name: 'Rebel Officer',
    slot: 'Personnel',
    points: 19,
    restrictions: { name: 'Rebel only', ldf: 'rebels' },
    description: 'Add 1 Rebel Officer mini.',
    keywords: ['Inspire 1', 'Leader'],
  },
  {
    ldf: 'rebelcommstechnician',
    name: 'Rebel Comms Technician',
    slot: 'Personnel',
    points: 9,
    restrictions: { name: 'Rebel only', ldf: 'rebels' },
    description:
      'Add 1 Rebel comms technician mini. You gain a comms upgrade icon. You must equip a comms upgrade card.',
  },
  {
    ldf: 'r5astromechdroid',
    name: 'R5 Astromech Droid',
    slot: 'Personnel',
    points: 8,
    restrictions: { name: 'Rebel only', ldf: 'rebels' },
    description: 'Add 1 R5 astromech mini.',
    keywords: ['Repair 1: Capacity 2', 'Noncombatant'],
  },
  {
    ldf: '21bmedicaldroid',
    name: '2-1B Medical Droid',
    slot: 'Personnel',
    points: 18,
    restrictions: { name: 'Rebel only', ldf: 'rebels' },
    description: 'Add 1 2-1B medical droid mini.',
    keywords: ['Treat 1: Capacity 2', 'Noncombatant'],
  },
  {
    ldf: 'imperialofficer',
    name: 'Imperial Officer',
    slot: 'Personnel',
    points: 20,
    restrictions: { name: 'Imperial only', ldf: 'empire' },
    description: 'Add 1 Imperial Officer mini.',
    keywords: ['Inspire 1', 'Leader'],
  },
  {
    ldf: 'imperialcommstechnician',
    name: 'Imperial Comms Technician',
    slot: 'Personnel',
    points: 10,
    restrictions: { name: 'Imperial only', ldf: 'empire' },
    description:
      'Add 1 Imperial comms technician mini. You gain a comms upgrade icon. You must equip a comms upgrade card.',
  },
  {
    ldf: 'r4astromechdroid',
    name: 'R4 Astromech Droid',
    slot: 'Personnel',
    points: 9,
    restrictions: { name: 'Imperial only', ldf: 'empire' },
    description: 'Add 1 R4 astromech mini.',
    keywords: ['Repair 1: Capacity 2', 'Noncombatant'],
  },
  {
    ldf: 'fx9medicaldroid',
    name: 'FX-9 Medical Droid',
    slot: 'Personnel',
    points: 19,
    restrictions: { name: 'Imperial only', ldf: 'empire' },
    description: 'Add 1 FX-9 medical droid mini.',
    keywords: ['Treat 1: Capacity 2', 'Noncombatant'],
  },
  {
    ldf: 'rebelveteran',
    name: 'Rebel Veteran',
    slot: 'Personnel',
    points: 12,
    restrictions: { name: 'Rebel Veterans only', ldf: 'rebelveterans' },
    description: 'Add 1 rebel veteran mini.',
  },
  {
    ldf: 'shoretrooper',
    name: 'Shoretrooper',
    slot: 'Personnel',
    points: 13,
    restrictions: { name: 'Shoretroopers only', ldf: 'shoretroopers' },
    description: 'Add 1 Shoretrooper mini.',
  },
  {
    ldf: 'phaseiclonetrooper',
    name: 'Phase I Clone Trooper',
    slot: 'Personnel',
    points: 13,
    restrictions: {
      name: 'Phase I Clone Troopers only',
      ldf: 'phaseiclonetroopers',
    },
    description: 'Add 1 Phase I Clone trooper mini.',
  },
  {
    ldf: 'b1battledroid',
    name: 'B1 Battle Droid',
    slot: 'Personnel',
    points: 6,
    restrictions: {
      name: 'B1 Battle Droids only',
      ldf: 'b1battledroids',
    },
    description: 'Add 1 B1 Battle Droid mini.',
  },
];

export default upgrades;
