import { Unit } from '../types';

const units: Unit[] = [
  {
    ldf: 'bobafett',
    unique: true,
    name: 'Boba Fett',
    subtitle: 'Infamous Bounty Hunter',
    factions: ["imperial"],
    type: 'Trooper',
    points: 160,
    rank: 'Operative',
    minis: 1,
    wounds: 5,
    courage: 3,
    defense: 'red',
    surge: { attack: 'crit', defense: 'block' },
    speed: 3,
    slots: ['Training', 'Training', 'Gear', 'Gear'],
    keywords: ['Jump 2', 'Arsenal 2', 'Sharpshooter 2', 'Bounty', 'Impervious'],
    weapons: [
      {
        name: 'Boot Spike',
        range: { from: 0 },
        dice: { red: 2 },
      },
      {
        name: "Fett's E-3 Carbine",
        range: { from: 1, to: 3 },
        dice: { black: 2 },
        keywords: ['Pierce 1'],
      },
      {
        name: 'Wrist Rocket',
        range: { from: 1, to: 2 },
        dice: { black: 2 },
        keywords: ['Impact 1'],
      },
    ],
    commandCards: ['whipcordlauncher', 'zxflameprojector', 'z6jetpackrocket'],
  },
  {
    ldf: 'chewbacca',
    name: 'Chewbacca',
    factions: ["rebel"],
    points: 95,
    printed_points: 110,
    rank: 'Operative',
    type: 'Trooper',
    minis: 1,
    wounds: 9,
    courage: 2,
    defense: 'white',
    surge: { attack: 'crit' },
    speed: 2,
    slots: ['Training', 'Training', 'Gear'],
    keywords: ['Enrage 4', 'Expert Climber', 'Guardian 3', 'Teamwork: Han Solo', 'Unhindered'],
    weapons: [
      {
        name: 'Overpower',
        range: { from: 0 },
        dice: { red: 4 },
      },
      {
        name: "Chewbacca's Bowcaster",
        range: { from: 1, to: 3 },
        dice: { red: 2, white: 2 },
        keywords: ['Impact 1', 'Pierce 1'],
      },
    ],
    commandCards: ['commoncause', 'brainsandbrawn', 'notoriousscoundrels'],
  },
  {
    ldf: 'sabinewren',
    name: 'Sabine Wren',
    factions: ["rebel"],
    points: 125,
    rank: 'Operative',
    type: 'Trooper',
    minis: 1,
    wounds: 5,
    courage: 2,
    defense: 'red',
    surge: { attack: 'crit', defense: 'block' },
    speed: 3,
    slots: ['Training', 'Gear', 'Gear', 'Armament'],
    keywords: ['Jump 2', 'Gunslinger', 'Impervious', 'Nimble'],
    weapons: [
      {
        name: 'Combat Expertise',
        range: { from: 0 },
        dice: { black: 2 },
      },
      {
        name: 'Dual Westar-35 Blaster Pistols',
        range: { from: 1, to: 2 },
        dice: { red: 1, black: 1, white: 1 },
        keywords: ['Pierce 1'],
      },
    ],
    commandCards: ['explosions', 'symbolofrebellion', 'legacyofmandalore'],
  },
  {
    ldf: 'bossk',
    name: 'Bossk',
    factions: ["imperial"],
    points: 115,
    rank: 'Operative',
    type: 'Trooper',
    minis: 1,
    wounds: 7,
    courage: 2,
    defense: 'white',
    surge: { attack: 'crit' },
    speed: 2,
    slots: ['Training', 'Training', 'Gear'],
    keywords: ['Bounty', 'Enrage', 'Expert Climber', 'Regenerate 3', 'Unhindered'],
    weapons: [
      {
        name: 'Frenzy',
        range: { from: 0, to: 0 },
        dice: { black: 2, red: 1, white: 1 },
        keywords: ['Pierce 1'],
      },
      {
        name: 'Relby-v10 Mortar Rifle',
        range: { from: 2, to: 4 },
        dice: { red: 1, white: 4 },
        keywords: ['Pierce 1', 'Suppressive'],
      },
    ],
    commandCards: ['mercilessmunitions', 'reptillianrampage', 'lyinginwait'],
  },
];

export default units;
