var units = [
    {
        ldf: 't47airspeeder',
        name: 'T-47 Airspeeder',
        factions: ['rebel'],
        points: 140,
        printed_points: 175,
        rank: 'Heavy',
        type: 'Repulsor Vehicle',
        minis: 1,
        wounds: 7,
        resilience: 5,
        defense: 'white',
        surge: { defense: 'block' },
        speed: 3,
        slots: ['Pilot', 'Hardpoint', 'Comms'],
        keywords: [
            'Armor',
            'Arsenal 2',
            'Cover 1',
            'Immune: Blast, Melee',
            'Speeder 2',
            'Immune: Range 1 Weapons',
        ],
        weapons: [
            {
                name: 'Ap/11 Double Laser Cannon',
                range: { from: 1, to: 3 },
                dice: { black: 3, red: 3 },
                keywords: ['Fixed: Front', 'Impact 3'],
            },
        ],
    },
    {
        ldf: 'atst',
        name: 'AT-ST',
        factions: ['imperial'],
        points: 170,
        printed_points: 195,
        rank: 'Heavy',
        type: 'Vehicle',
        minis: 1,
        wounds: 11,
        resilience: 8,
        defense: 'white',
        surge: { defense: 'block' },
        speed: 2,
        slots: ['Pilot', 'Hardpoint', 'Hardpoint', 'Hardpoint', 'Comms'],
        keywords: ['Armor', 'Arsenal 2', 'Weak Point 1: Rear'],
        weapons: [
            {
                name: 'Fence-Cutting Blades',
                range: { from: 0 },
                dice: { red: 4 },
            },
            {
                name: 'MS-4 Twin Blaster Cannon',
                range: { from: 1, to: 4 },
                dice: { red: 2, black: 2, white: 2 },
                keywords: ['Fixed: Front', 'Impact 3'],
            },
        ],
    },
    {
        ldf: 'tx225gavwoccupiercombatassaulttank',
        name: 'TX-225 GAVw Occupier Combat Assault Tank',
        factions: ['imperial'],
        points: 155,
        rank: 'Heavy',
        type: 'Vehicle',
        minis: 1,
        wounds: 8,
        resilience: 6,
        defense: 'red',
        surge: {},
        speed: 1,
        slots: ['Comms', 'Hardpoint', 'Pilot'],
        keywords: [
            'Armor',
            'Arsenal 2',
            'Weak Point 1: Sides',
            'Reposition',
            'Transport 1: Open',
        ],
        weapons: [
            {
                name: 'Forward Twin MK 2E/W Cannons',
                range: { from: 1, to: 2 },
                dice: { black: 1, red: 1 },
                keywords: ['Suppressive', 'Fixed: Front'],
            },
            {
                name: 'Lateral Quad MK 2E/W Cannons',
                range: { from: 1, to: 4 },
                dice: { black: 2, red: 2 },
                keywords: ['Impact 2', 'Fixed: Front'],
            },
        ],
    },
    {
        ldf: 'x34landspeeder',
        name: 'X-34 Landspeeder',
        factions: ['rebel'],
        points: 75,
        rank: 'Heavy',
        type: 'Repulsor Vehicle',
        minis: 1,
        wounds: 6,
        resilience: 4,
        defense: 'white',
        surge: { attack: 'hit', defense: 'block' },
        speed: 2,
        slots: ['Comms', 'Crew', 'Crew', 'Hardpoint', 'Pilot'],
        keywords: [
            'Armor 2',
            'Arsenal 3',
            'Cover 1',
            'Light Transport 1: Open',
            'Speeder 1',
        ],
        weapons: [
            {
                name: "Driver's DH- 17 Blaster Pistol",
                range: { from: 1, to: 2 },
                dice: { white: 1 },
            },
        ],
    },
    {
        ldf: 'aattradefederationbattletank',
        name: 'AAT Trade Federation Battle Tank',
        factions: ['separatist'],
        points: 170,
        rank: 'Heavy',
        type: 'Repulsor Vehicle',
        minis: 1,
        wounds: 9,
        resilience: 6,
        defense: 'red',
        surge: {},
        speed: 1,
        slots: ['Comms', 'Pilot', 'Ordnance', 'Ordnance'],
        keywords: [
            'AI: Attack',
            'Armor',
            'Arsenal 2',
            'Weak Point 2: Rear',
            'Barrage',
            'Hover: Ground',
        ],
        weapons: [
            {
                name: 'Lateral Anti-Personnel Lasers',
                range: { from: 1, to: 2 },
                dice: { black: 3 },
                keywords: ['Fixed: Front'],
            },
            {
                name: 'MX-8 Artillery Laser Cannon',
                range: { from: 2, to: 4 },
                dice: { red: 4 },
                keywords: ['Critical 2', 'Impact 1', 'High Velocity'],
            },
        ],
    },
    {
        ldf: 'tx130saberclassfightertank',
        name: 'TX-130 Saber-class Fighter Tank',
        factions: ['republic'],
        points: 170,
        rank: 'Heavy',
        type: 'Repulsor Vehicle',
        minis: 1,
        wounds: 9,
        resilience: 6,
        defense: 'red',
        surge: {},
        speed: 2,
        slots: ['Hardpoint', 'Pilot', 'Ordnance', 'Comms'],
        keywords: [
            'AI: Attack',
            'Armor',
            'Arsenal 2',
            'Weak Point 2: Rear',
            'Barrage',
            'Hover: Ground',
        ],
        weapons: [
            {
                name: 'Twin Lateral GA-6w Lasers Cannons',
                range: { from: 1, to: 4 },
                dice: { white: 2, black: 2, red: 2 },
                keywords: ['Critical 1', 'Impact 2', 'Fixed: Front'],
            },
        ],
    },
];
export default units;
//# sourceMappingURL=heavy.js.map