var units = [
    {
        ldf: 'rebelcommandos',
        name: 'Rebel Commandos',
        factions: ["rebel"],
        points: 60,
        rank: 'Special Forces',
        type: 'Trooper',
        minis: 4,
        wounds: 1,
        courage: 2,
        defense: 'white',
        surge: { attack: 'hit', defense: 'block' },
        speed: 2,
        slots: ['Heavy Weapon', 'Training', 'Comms', 'Gear', 'Grenades'],
        keywords: ['Low Profile', 'Scout 2', 'Sharpshooter 1'],
        weapons: [
            {
                name: 'Unarmed',
                range: { from: 0 },
                dice: { black: 1 },
            },
            {
                name: 'A-280 Blaster Rifle',
                range: { from: 1, to: 3 },
                dice: { black: 1 },
            },
        ],
    },
    {
        ldf: 'rebelcommandosstriketeam',
        name: 'Rebel Commandos Strike Team',
        factions: ["rebel"],
        points: 20,
        printed_points: 16,
        rank: 'Special Forces',
        type: 'Trooper',
        minis: 1,
        wounds: 1,
        courage: 2,
        defense: 'white',
        surge: { attack: 'hit', defense: 'block' },
        speed: 2,
        slots: ['Heavy Weapon', 'Training', 'Comms', 'Gear', 'Grenades'],
        keywords: ['Heavy Weapon Team', 'Low Profile', 'Scout 2', 'Sharpshooter 1'],
        weapons: [
            {
                name: 'Unarmed',
                range: { from: 0 },
                dice: { black: 1 },
            },
            {
                name: 'A-280 Blaster Rifle',
                range: { from: 1, to: 3 },
                dice: { black: 1 },
            },
        ],
    },
    {
        ldf: 'scouttroopers',
        name: 'Scout Troopers',
        factions: ["imperial"],
        points: 60,
        rank: 'Special Forces',
        type: 'Trooper',
        minis: 4,
        wounds: 1,
        courage: 2,
        defense: 'white',
        surge: { defense: 'block' },
        speed: 2,
        slots: ['Heavy Weapon', 'Training', 'Comms', 'Gear', 'Grenades'],
        keywords: ['Low Profile', 'Scout 1', 'Sharpshooter 1'],
        weapons: [
            {
                name: 'Unarmed',
                range: { from: 0 },
                dice: { black: 1 },
            },
            {
                name: 'EC-17 Holdout Blaster',
                range: { from: 1, to: 2 },
                dice: { black: 2 },
            },
        ],
    },
    {
        ldf: 'scouttroopersstriketeam',
        name: 'Scout Troopers Strike Team',
        factions: ["imperial"],
        points: 20,
        printed_points: 16,
        rank: 'Special Forces',
        type: 'Trooper',
        minis: 1,
        wounds: 1,
        courage: 2,
        defense: 'white',
        surge: { defense: 'block' },
        speed: 2,
        slots: ['Heavy Weapon', 'Training', 'Comms', 'Gear', 'Grenades'],
        keywords: ['Heavy Weapon Team', 'Low Profile', 'Scout 1', 'Sharpshooter 1'],
        weapons: [
            {
                name: 'Unarmed',
                range: { from: 0 },
                dice: { black: 1 },
            },
            {
                name: 'EC-17 Holdout Blaster',
                range: { from: 1, to: 2 },
                dice: { black: 2 },
            },
        ],
    },
    {
        ldf: 'wookieewarriors',
        name: 'Wookiee Warriors',
        factions: ["rebel"],
        points: 75,
        rank: 'Special Forces',
        type: 'Trooper',
        minis: 3,
        wounds: 3,
        courage: 2,
        defense: 'white',
        surge: { attack: 'hit' },
        speed: 2,
        slots: ['Heavy Weapon', 'Training', 'Training', 'Gear', 'Grenades'],
        keywords: ['Charge', 'Expert Climber', 'Indomitable', 'Unhindered'],
        weapons: [
            {
                name: 'Ryyk Blade',
                range: { from: 0 },
                dice: { black: 2 },
            },
            {
                name: 'Kashyyyk Pistol',
                range: { from: 1, to: 2 },
                dice: { black: 2, white: 1 },
            },
        ],
    },
    {
        ldf: 'imperialroyalguards',
        name: 'Imperial Royal Guards',
        factions: ["imperial"],
        points: 75,
        rank: 'Special Forces',
        type: 'Trooper',
        minis: 3,
        wounds: 2,
        courage: 2,
        defense: 'red',
        surge: {},
        speed: 2,
        slots: ['Heavy Weapon', 'Training', 'Comms', 'Gear', 'Grenades'],
        keywords: ['Charge', 'Disciplined 2', 'Guardian 2'],
        weapons: [
            {
                name: 'Force Pike',
                range: { from: 0 },
                dice: { red: 1, black: 1 },
            },
            {
                name: 'EC-17 Holdout Blaster',
                range: { from: 1, to: 2 },
                dice: { black: 2 },
            },
        ],
    },
    {
        ldf: 'rebelpathfinders',
        name: 'Rebel Pathfinders',
        factions: ["rebel"],
        points: 60,
        rank: 'Special Forces',
        type: 'Trooper',
        minis: 4,
        wounds: 1,
        courage: 2,
        defense: 'white',
        surge: { attack: 'hit', defense: 'block' },
        speed: 2,
        slots: [
            'Armament',
            'Comms',
            'Gear',
            'Grenades',
            'Heavy Weapon',
            'Training',
        ],
        keywords: ['Danger Sense 3', 'Dauntless', 'Infiltrate'],
        weapons: [
            {
                name: 'Unarmed',
                range: { from: 0 },
                dice: { black: 1 },
            },
            {
                name: 'A-300 Blaster Rifle',
                range: { from: 1, to: 3 },
                dice: { white: 2 },
            },
        ],
    },
    {
        ldf: 'imperialdeathtroopers',
        name: 'Imperial Death Troopers',
        factions: ["imperial"],
        points: 76,
        rank: 'Special Forces',
        type: 'Trooper',
        minis: 4,
        wounds: 1,
        courage: 2,
        defense: 'white',
        surge: { attack: 'hit', defense: 'block' },
        speed: 2,
        slots: [
            'Armament',
            'Comms',
            'Gear',
            'Grenades',
            'Heavy Weapon',
            'Training',
        ],
        keywords: ['Disciplined 1', 'Precise 2', 'Ready 1'],
        weapons: [
            {
                name: 'Close Quarters Combat',
                range: { from: 0 },
                dice: { red: 1 },
            },
            {
                name: 'SE-14r Light Blaster',
                range: { from: 1, to: 2 },
                dice: { white: 2 },
            },
            {
                name: 'E-11D Blaster Rifle',
                range: { from: 1, to: 3 },
                dice: { black: 1 },
            },
        ],
    },
    {
        ldf: 'bxseriesdroidcommandosstriketeam',
        name: 'BX-Series Droid Commandos Strike Team',
        factions: ['separatist'],
        points: 68,
        rank: 'Special Forces',
        type: 'Droid Trooper',
        minis: 1,
        wounds: 1,
        courage: 2,
        defense: 'red',
        surge: {},
        speed: 3,
        slots: [
            'Heavy Weapon',
        ],
        keywords: ['AI: Dodge, Move', 'Heavy Weapon Team', 'Impervious', 'Scale', 'Scout 3', 'Sharpshooter 1'],
        weapons: [
            {
                name: 'Unarmed',
                range: { from: 0 },
                dice: { black: 1 },
            },
            {
                name: 'Commando E-5 Blaster Rifle',
                range: { from: 1, to: 3 },
                dice: { white: 1 },
            },
        ],
    },
    {
        ldf: 'bxseriesdroidcommandos',
        name: 'BX-Series Droid Commandos',
        factions: ['separatist'],
        points: 68,
        rank: 'Special Forces',
        type: 'Droid Trooper',
        minis: 4,
        wounds: 1,
        courage: 2,
        defense: 'red',
        surge: {},
        speed: 3,
        slots: [
            'Heavy Weapon',
            'Training',
        ],
        keywords: ['AI: Dodge, Move', 'Impervious'],
        weapons: [
            {
                name: 'Unarmed',
                range: { from: 0 },
                dice: { black: 1 },
            },
        ],
    },
    {
        ldf: 'arctroopersstriketeam',
        name: 'ARC Troopers Strike Team',
        factions: ['republic'],
        points: 76,
        rank: 'Special Forces',
        type: 'Clone Trooper',
        minis: 1,
        wounds: 1,
        courage: 2,
        defense: 'red',
        surge: {},
        speed: 2,
        slots: [
            'Comms',
            'Gear',
            'Gear',
            'Grenades',
            'Heavy Weapon',
            'Training',
        ],
        keywords: ['Heavy Weapon Team', 'Scout 2', 'Impervious', 'Sharpshooter 1', 'Tactical 1'],
        weapons: [
            {
                name: 'Combat Training',
                range: { from: 0 },
                dice: { black: 1, white: 1 },
            },
            {
                name: 'DC-17 Hand Blasters',
                range: { from: 1, to: 2 },
                dice: { black: 1, white: 1 },
            },
            {
                name: 'DC-15A Blaster Rifle',
                range: { from: 1, to: 3 },
                dice: { black: 1 },
            },
        ],
    },
    {
        ldf: 'arctroopers',
        name: 'ARC Troopers',
        factions: ['republic'],
        points: 72,
        rank: 'Special Forces',
        type: 'Clone Trooper',
        minis: 4,
        wounds: 1,
        courage: 2,
        defense: 'red',
        surge: {},
        speed: 2,
        slots: [
            'Comms',
            'Gear',
            'Gear',
            'Grenades',
            'Heavy Weapon',
            'Training',
        ],
        keywords: ['Scout 2', 'Impervious', 'Sharpshooter 1', 'Tactical 1'],
        weapons: [
            {
                name: 'Combat Training',
                range: { from: 0 },
                dice: { black: 1, white: 1 },
            },
            {
                name: 'DC-17 Light Blaster',
                range: { from: 1, to: 2 },
                dice: { black: 1, white: 1 },
            },
            {
                name: 'DC-15A Blaster Rifle',
                range: { from: 1, to: 3 },
                dice: { black: 1 },
            },
        ],
    },
];
export default units;
//# sourceMappingURL=special.js.map